/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaGalleryIndexRouteImport } from './routes/media-gallery/index'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as FoldersIndexRouteImport } from './routes/folders/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as ItemsItemIdRouteImport } from './routes/items/$itemId'
import { Route as FoldersFolderIdRouteImport } from './routes/folders/$folderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaGalleryIndexRoute = MediaGalleryIndexRouteImport.update({
  id: '/media-gallery/',
  path: '/media-gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersIndexRoute = FoldersIndexRouteImport.update({
  id: '/folders/',
  path: '/folders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdRoute = ItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersFolderIdRoute = FoldersFolderIdRouteImport.update({
  id: '/folders/$folderId',
  path: '/folders/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/auth': typeof AuthIndexRoute
  '/folders': typeof FoldersIndexRoute
  '/items': typeof ItemsIndexRoute
  '/media-gallery': typeof MediaGalleryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/auth': typeof AuthIndexRoute
  '/folders': typeof FoldersIndexRoute
  '/items': typeof ItemsIndexRoute
  '/media-gallery': typeof MediaGalleryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/auth/': typeof AuthIndexRoute
  '/folders/': typeof FoldersIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/media-gallery/': typeof MediaGalleryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/folders/$folderId'
    | '/items/$itemId'
    | '/auth'
    | '/folders'
    | '/items'
    | '/media-gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/folders/$folderId'
    | '/items/$itemId'
    | '/auth'
    | '/folders'
    | '/items'
    | '/media-gallery'
  id:
    | '__root__'
    | '/'
    | '/folders/$folderId'
    | '/items/$itemId'
    | '/auth/'
    | '/folders/'
    | '/items/'
    | '/media-gallery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoldersFolderIdRoute: typeof FoldersFolderIdRoute
  ItemsItemIdRoute: typeof ItemsItemIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
  FoldersIndexRoute: typeof FoldersIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  MediaGalleryIndexRoute: typeof MediaGalleryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-gallery/': {
      id: '/media-gallery/'
      path: '/media-gallery'
      fullPath: '/media-gallery'
      preLoaderRoute: typeof MediaGalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/': {
      id: '/folders/'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof FoldersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemId': {
      id: '/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$folderId': {
      id: '/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof FoldersFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoldersFolderIdRoute: FoldersFolderIdRoute,
  ItemsItemIdRoute: ItemsItemIdRoute,
  AuthIndexRoute: AuthIndexRoute,
  FoldersIndexRoute: FoldersIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  MediaGalleryIndexRoute: MediaGalleryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
